"""
30-prompt test suite — easy / medium / hard
Covers summarization, reasoning, structured extraction, code gen
"""

PROMPTS = [
    # ── EASY (1-10) — factual, short answer ──────────────────────
    {"id": "e01", "difficulty": "easy", "task": "factual",
     "prompt": "What is the capital of France?"},
    {"id": "e02", "difficulty": "easy", "task": "factual",
     "prompt": "What does CPU stand for?"},
    {"id": "e03", "difficulty": "easy", "task": "factual",
     "prompt": "What is 17 multiplied by 13?"},
    {"id": "e04", "difficulty": "easy", "task": "factual",
     "prompt": "Name three programming languages used for web development."},
    {"id": "e05", "difficulty": "easy", "task": "factual",
     "prompt": "What is the time complexity of binary search?"},
    {"id": "e06", "difficulty": "easy", "task": "factual",
     "prompt": "What does HTTP stand for?"},
    {"id": "e07", "difficulty": "easy", "task": "factual",
     "prompt": "What is a Python list comprehension? Give one example."},
    {"id": "e08", "difficulty": "easy", "task": "factual",
     "prompt": "What is the difference between a stack and a queue?"},
    {"id": "e09", "difficulty": "easy", "task": "factual",
     "prompt": "What does git commit do?"},
    {"id": "e10", "difficulty": "easy", "task": "factual",
     "prompt": "What is an API?"},

    # ── MEDIUM (11-20) — reasoning, summarization ─────────────────
    {"id": "m01", "difficulty": "medium", "task": "reasoning",
     "prompt": "Explain why quicksort has O(n log n) average case but O(n²) worst case."},
    {"id": "m02", "difficulty": "medium", "task": "reasoning",
     "prompt": "What are the tradeoffs between SQL and NoSQL databases? Give 3 tradeoffs."},
    {"id": "m03", "difficulty": "medium", "task": "summarization",
     "prompt": "Summarize the key ideas behind transformer architecture in 5 bullet points."},
    {"id": "m04", "difficulty": "medium", "task": "reasoning",
     "prompt": "Explain the difference between concurrency and parallelism with examples."},
    {"id": "m05", "difficulty": "medium", "task": "reasoning",
     "prompt": "Why is gradient descent used in machine learning? What problem does it solve?"},
    {"id": "m06", "difficulty": "medium", "task": "summarization",
     "prompt": "Explain REST API design principles in plain English."},
    {"id": "m07", "difficulty": "medium", "task": "reasoning",
     "prompt": "What is the difference between authentication and authorization?"},
    {"id": "m08", "difficulty": "medium", "task": "reasoning",
     "prompt": "Explain how a hash table works and what happens during a collision."},
    {"id": "m09", "difficulty": "medium", "task": "code",
     "prompt": "Write a Python function to check if a string is a palindrome."},
    {"id": "m10", "difficulty": "medium", "task": "code",
     "prompt": "Write a Python function that returns the nth Fibonacci number using memoization."},

    # ── HARD (21-30) — structured output, complex reasoning ───────
    {"id": "h01", "difficulty": "hard", "task": "structured",
     "prompt": "Extract the following fields from this text as JSON: name, role, company, location. Text: 'Aayushmaan Chakraborty is applying for a Software Engineering Intern role at Google LLC in Bengaluru, Karnataka, India.'"},
    {"id": "h02", "difficulty": "hard", "task": "structured",
     "prompt": "Convert this to a JSON array of objects with fields 'item' and 'price': Apples: $1.20, Bananas: $0.50, Oranges: $0.90, Grapes: $2.40"},
    {"id": "h03", "difficulty": "hard", "task": "reasoning",
     "prompt": "Design a rate limiter for an API that allows 100 requests per minute per user. Explain the algorithm and data structures you would use."},
    {"id": "h04", "difficulty": "hard", "task": "code",
     "prompt": "Write a Python class implementing a thread-safe LRU cache with get and put methods."},
    {"id": "h05", "difficulty": "hard", "task": "reasoning",
     "prompt": "Explain how you would design a URL shortener like bit.ly. Cover the database schema, hashing strategy, and scalability."},
    {"id": "h06", "difficulty": "hard", "task": "structured",
     "prompt": "Parse this log line into JSON with fields: timestamp, level, service, message. Log: '2026-06-27 14:23:01 ERROR auth-service Failed to validate token for user_id=4821'"},
    {"id": "h07", "difficulty": "hard", "task": "reasoning",
     "prompt": "What are the SOLID principles? Give a one-sentence explanation and a Python example for each."},
    {"id": "h08", "difficulty": "hard", "task": "code",
     "prompt": "Write a Python function that flattens a nested dictionary. Example: {'a': {'b': {'c': 1}}} becomes {'a.b.c': 1}"},
    {"id": "h09", "difficulty": "hard", "task": "reasoning",
     "prompt": "Explain the CAP theorem. Give a real-world example for each combination of two properties."},
    {"id": "h10", "difficulty": "hard", "task": "structured",
     "prompt": "Given this JSON, return only the users where age > 25 as a filtered JSON array: [{\"name\":\"Alice\",\"age\":30},{\"name\":\"Bob\",\"age\":22},{\"name\":\"Carol\",\"age\":27}]"},
]
